services:
  db:
    image: postgres:latest
<<<<<<< HEAD
    container_name: "infocenter_db"
=======
    container_name: "infocenter"
>>>>>>> 7abd66c (fix login function and change books pagination)
    environment:
      - POSTGRES_USER=infocenter-admin
      - POSTGRES_PASSWORD=infocenter@123
      - POSTGRES_DB=infocenter
    ports:
      - "5432:5432"
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - db
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
